Repository rsksmart/rconnect, pull requests merged in 2020-04, with the labels that each got.

#1 RIFEX-58 Fixing node version
  package-lock.json
  package.json
Labels: bug

#2 Feature/RIFEX-28/Dropdown-item-with-icon
  old-ui/app/app.js
  old-ui/app/components/app-bar/main-menu.js
  old-ui/app/components/dropdown.js
  package.json
  ui/app/reducers/app.js
  ui/app/rif/actions.js
  ui/app/rif/pages/domainsPage.js
  ui/app/rif/pages/paymentsPage.js
Labels: enhancement

#5 Feature/rifex 21/adding confirmation message component
  .gitignore
  gulpfile.js
  old-ui/app/app.js
  old-ui/css.js
  package.json
  ui/app/reducers/app.js
  ui/app/rif/actions.js
  ui/app/rif/components/confirmationMessage/confirmationMessage.css
  ui/app/rif/components/confirmationMessage/confirmationMessage.js
Labels: enhancement

#3 Feature/rifex-32/Domains-Page
  old-ui/app/app.js
  old-ui/app/css/rif.css
  ui/app/rif/components/index.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/pages/domainsPage.js
  ui/app/rif/pages/domainsPage/domain-page.css
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/paymentsPage/paymentsPage.js
  ui/app/rif/test/mocks.js
Labels: enhancement

#6 Feature/Rifex-37/Add-new-multicrypto-network-address
  old-ui/app/app.js
  ui/app/reducers/app.js
  ui/app/rif/actions.js
  ui/app/rif/components/commons/icons.js
  ui/app/rif/components/commons/index.js
  ui/app/rif/components/index.js
  ui/app/rif/components/modal/addNewTokenNetworkAddress/addNewTokenNetworkAddress.js
  ui/app/rif/components/modal/addNewTokenNetworkAddress/modal-add-new-network-address.css
  ui/app/rif/components/modal/modal.css
  ui/app/rif/components/modal/modal.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainsDetailPage.js
  ui/app/rif/pages/domainsPage/domainsPage.js
Labels: enhancement, ui

#9 Feature/RIFEX-62/Available-domain-search
  .gitignore
  ui/app/rif/actions.js
  ui/app/rif/components/searchDomains.js
Labels: enhancement, rns, ui

#11 RIFEX-60 Register a new domain
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  old-ui/app/account-detail.js
  old-ui/app/app.js
  old-ui/app/conf-tx.js
  ui/app/actions.js
  ui/app/reducers/app.js
  ui/app/rif/actions.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/index.js
  ui/app/rif/pages/rns/domains/register/index.css
  ui/app/rif/pages/rns/domains/register/index.js
Labels: enhancement, rns, service layer, ui

#12 Feature/rifex 38/adding rns menu and blank screens
  old-ui/app/app.js
  old-ui/app/components/app-bar/main-menu.js
  ui/app/reducers/app.js
  ui/app/rif/actions.js
  ui/app/rif/components/index.js
  ui/app/rif/components/menu/index.css
  ui/app/rif/components/menu/index.js
  ui/app/rif/components/modal/modal.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainsDetailPage.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/rns/exchange/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/pages/rns/register/index.css
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/pages/rns/renew/index.js
  ui/app/rif/pages/rns/sell-on-mkp/index.js
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/pages/rns/transfer/index.js
  ui/app/rif/reducers/index.js
Labels: enhancement, refactor, rns, ui
