Repository rsksmart/rconnect, pull requests merged in 2020-07, with the labels that each got.

#89 bufix/rsk-network
  app/scripts/controllers/rif/configuration/index.js
  app/scripts/controllers/rif/index.js
Labels: bug, service layer

#90 Feature/rifex 103 - Selector of Tokens styles
  ui/app/rif/components/lumino/open-channel/index.css
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
Labels: ui

#92 RIFEX-178 Remove Leave button
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
Labels: ui

#91 Bugfix/error messages
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/utils/parse.js
Labels: bug

#88 RIFEX-168/Notifier-Chainaddresses
  app/scripts/controllers/rif/abstract-manager.js
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/notifier/index.js
  app/scripts/controllers/rif/notifier/operations.js
  app/scripts/controllers/rif/notifier/signing-handler.js
  app/scripts/controllers/rif/rns/index.js
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  ui/app/constants/common.js
  ui/app/rif/components/chainAddresses.js
Labels: enhancement, refactor, service layer

#93 Fixing ChainAddresses component naming
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
Labels: bug

#94 RIFEX-186 Callback errors for deposit and close channel
  app/scripts/controllers/rif/constants/lumino.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: bug, service layer, ui

#95 RIFEX-197/Add-Address-Button-Fix
  app/scripts/controllers/rif/rns/resolver/index.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/utils/utils.js
Labels: bug, enhancement, ui

#96 RIFEX-185 Subscribe to close channel error
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
Labels: bug

#97 RIFEX-197/Not-Showing-Chainaddresses
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
Labels: bug, ui

#99 Added space between balance and token symbol
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: enhancement, ui

#98 RIFEX-165 Fixing navigation and register errors
  app/scripts/controllers/rif/rns/register/index.js
  old-ui/app/components/account-dropdowns/account-dropdowns.component.js
  old-ui/app/components/app-bar/networks-menu.js
  ui/app/rif/actions/index.js
  ui/app/rif/pages/domainsPage/domain-page.css
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/rns/register/index.js
Labels: bug, rns, service layer, ui

#104 Feat/rifex 212 Do not truncate partner address in channel detail
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/pages/rns/lumino-channels/index.css
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: ui

#102 RIFEX-207/Pending-Subdomains
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: enhancement, ui

#101 RIFEX-209/210/213 Loading states for channel actions and SDK actions
  mascara/src/app/first-time/index.css
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/components/luminoChannelItem/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/utils/utils.js
Labels: enhancement, ui

#103 RIFEX-147/Icons-Slipaddresses
  app/images/rif/bitcoin.svg
  app/images/rif/bitcoincash.svg
  app/images/rif/coinstack.svg
  app/images/rif/dash.svg
  app/images/rif/decred.svg
  app/images/rif/eos.svg
  app/images/rif/ethereum.svg
  app/images/rif/ethereumclassic.svg
  app/images/rif/litecoin.svg
  app/images/rif/monacoin.svg
  app/images/rif/monero.svg
  app/images/rif/nem.svg
  app/images/rif/neo.svg
  app/images/rif/rbtc.png
  app/images/rif/ripple.svg
  app/images/rif/rsk.svg
  app/images/rif/tezos.svg
  app/images/rif/tron.svg
  app/images/rif/zcash.svg
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/constants/icons.js
  ui/app/rif/constants/index.js
  ui/app/rif/constants/slipAddresses.js
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
Labels: enhancement, ui

#100 Bug/rifex 182/fixing listeners
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  app/scripts/controllers/rif/transaction-listener.js
Labels: bug, rns, service layer, ui

#105 RIFEX-214/Search-Domain-No-Owner
  ui/app/rif/components/searchDomains.js
  ui/app/rif/pages/configuration/index.js
Labels: bug, ui

#110 RIFEX-222 Open and Close channels fail when the address is a rns domain
  app/scripts/controllers/rif/lumino/operations.js
Labels: bug

#106 RIFEX-218 Fix css for Lumino spinners
  mascara/src/app/first-time/index.css
  ui/app/rif/pages/common-style-pages.css
Labels: ui

#108 RIFEX-221 Fix Close channel spinner message
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: bug, ui

#107 RIFEX-220 Fixing pending registration timeout redirect
  ui/app/rif/pages/rns/register/index.js
Labels: bug, ui

#109 RIFEX-217/Pending-store-improvement
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  ui/app/constants/common.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/utils/utils.js
Labels: bug, service layer, ui

#112 RIFEX-223/Missed-inicialization-pendingChainAddresses
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
Labels: bug, service layer

#111 Bug/rifex 191/fixing nifty confirmation page
  old-ui/app/conf-tx.js
  ui/app/actions.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: bug

#113 RIFEX-225/Pending-Reject
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
Labels: bug, service layer

#114 Fixing pending bug when we change of account
  app/scripts/controllers/rif/rns/resolver/index.js
Labels: bug

#117 RIFEX-239 Correct operation times
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
Labels: ui

#115 RIFEX-235, Change the color on inputs
  ui/app/rif/pages/rns/pay/index.css
  ui/app/rif/styleTemplate/template.css
Labels: bug, refactor, ui

#116 RIFEX-231 Fixing no resolver bug
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/utils/parse.js
Labels: bug, ui

#120 RIFEX-232 RNS Payment network select styles
  ui/app/rif/components/networks-dropdown/index.css
  ui/app/rif/components/networks-dropdown/index.js
Labels: bug, ui

#118 RIFEX-228 Improve Domain payment experience
  ui/app/rif/pages/rns/pay/index.js
Labels: enhancement, ui

#119 RIFEX-230 RNS Payment Tokens select styles
  ui/app/rif/components/tokens-dropdown/index.css
  ui/app/rif/components/tokens-dropdown/index.js
Labels: bug, ui

#121 Bug/rifex 240/fixing ui callbacks
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/utils/utils.js
Labels: bug, ui

#122 RIFEX-242/Setting-multichain-back-action
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
Labels: bug

#123 RIFEX-244/Chainaddresses-pending
  app/scripts/controllers/rif/rns/resolver/index.js
Labels: bug, service layer

#124 RIFEX-246/Incorrect-numbers-nodes
  app/scripts/controllers/rif/lumino/explorer.js
  ui/app/rif/actions/index.js
Labels: bug, service layer, ui

#126 RIFEX-251/NotOwner-Not-showing-chainaddresses
  app/scripts/controllers/rif/rns/resolver/index.js
Labels: bug, service layer

#125 RIFEX-243/Pending-duplicated-Chainaddress
  app/scripts/controllers/rif/rns/resolver/index.js
Labels: bug, ui

#128 RIFEX-255/Priority-icons
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/constants/slipAddresses.js
Labels: enhancement, ui

#127 RIFEX-248/Clicking-domain-tab
  ui/app/rif/components/tabs/index.js
  ui/app/rif/pages/domainsPage/domainsPage.js
Labels: bug, ui

#130 Bug/rifex 257/fixing init config bug
  app/scripts/controllers/rif/configuration/index.js
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/rns/index.js
  ui/app/rif/pages/configuration/index.js
Labels: bug, service layer, ui

#131 RIFEX-258/Backbutton-domain-requested
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/rns/register/index.js
Labels: bug, ui

#129 RIFEX-262/Subdomain-Clickeable
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
Labels: bug, ui

#132 RIFEX-249 Fixing register bugs
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/rns/register/index.js
Labels: bug, rns, service layer, ui

#135 RIFEX-259/Delete-as-domain-owner-subdomain
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: enhancement, ui

#134 RIFEX-260/Indicator-Pending-Set-Resolver
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
Labels: enhancement, service layer, ui

#136 RIFEX-263/Open-channel-lumino-home
  ui/app/rif/pages/lumino/index.js
Labels: enhancement, ui

#139 RIFEX-49/Edit-subdomains
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  app/scripts/controllers/rif/utils/rns.js
  ui/app/constants/common.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: enhancement, ui

#138 RIFEX-265/Clickable-channels
  ui/app/rif/components/luminoChannelItem/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
Labels: enhancement, ui

#137 RIFEX-264/Clickable-network-rows
  ui/app/rif/components/LuminoNetworkItem/index.js
  ui/app/rif/pages/lumino/index.js
Labels: enhancement, ui

#144 Rifex 270/subdomain-pointer
  ui/app/rif/pages/rns/subdomains/index.js
Labels: bug, ui

#145 RIFEX-269/Check-correct-address
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
Labels: bug, ui

#143 RIFEX-272/Subdomain-no-scrolleable
  app/scripts/controllers/rif/rns/resolver/index.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: bug, ui

#146 RIFEX-275/Searchbar-delete-placeholder
  ui/app/rif/components/subDomains.js
Labels: enhancement, ui

#149 RIFEX-279/Change-isAddressWeb3-Rskjutils
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  package.json
Labels: bug, service layer

#147 RIFEX-267 fixing registration without rif tokens
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/transaction-listener.js
  old-ui/app/account-detail.js
  ui/app/rif/actions/index.js
  ui/app/rif/pages/abstract-page.js
  ui/app/rif/pages/rns/register/index.js
Labels: bug, rns, service layer, ui

#150 RIFEX-26/fix-landing-back-navigation
  ui/app/rif/actions/index.js
Labels: bug, ui

#151 RIFEX-286/Search-domain-onregister
  ui/app/rif/pages/rns/register/index.js
Labels: bug, ui

#153 RIFEX-276/Navigation-after-register
  ui/app/rif/pages/rns/register/index.js
Labels: bug, ui

#148 RIFEX-272/Add-channel-button
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, ui

#155 RIFEX-288 and RIFEX-287 Fixing deposit update bugs
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: bug, ui

#152 Fix RIFEX-284/token-combobox
  ui/app/rif/pages/lumino/index.js
Labels: bug, ui

#154 RIFEX-285/modal-too-big
  ui/app/rif/components/modal/modal.css
Labels: bug, ui

#156 RIFEX-268/trim-subdomain-name
  ui/app/rif/components/table/index.css
Labels: bug, ui

#157 RIFEX-268/trim-subdomain-name
  ui/app/rif/components/table/index.css
Labels: bug, ui

#158 RIFEX-289 Fixing reject all
  old-ui/app/conf-tx.js
Labels: bug, ui

#159 RIFEX-293/EditAdd-chainaddress-same-value
  ui/app/rif/components/chainAddresses.js
Labels: bug, ui
