Repository rsksmart/rconnect, pull requests merged in 2020-08, with the labels that each got.

#140 Feature/rifex 266/adding multilanguage support
  README.md
  i18n.js
  languages/en.json
  languages/es.json
  languages/index.js
  old-ui/app/account-detail.js
  old-ui/app/app.js
  old-ui/app/components/account-dropdowns/account-dropdowns.component.js
  old-ui/app/components/add-token/add-token.component.js
  old-ui/app/components/app-bar/main-menu.js
  old-ui/app/components/notice.js
  old-ui/app/components/token-list.js
  old-ui/app/components/transaction-list.js
  old-ui/app/config.js
  old-ui/app/first-time/init-menu.js
  old-ui/app/keychains/hd/restore-vault.js
  old-ui/app/unlock.js
  package.json
  ui/app/rif/actions/index.js
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/LuminoNetworkItem/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/components/luminoChannelItem/index.js
  ui/app/rif/components/luminoChannels.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/menu/index.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/components/searchLuminoNetworks/index.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/components/table/genericTable.js
  ui/app/rif/components/tokenNetworkChannels.js
  ui/app/rif/components/tokens/ChannelChiplet.js
  ui/app/rif/pages/abstract-page.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/configuration/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/domainsDetailPage/domainExpired/domainExpired.js
  ui/app/rif/pages/domainsDetailPage/domainExpiring/domainExpiring.js
  ui/app/rif/pages/domainsDetailPage/domainsDetailPage.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/exchange/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/pages/rns/renew/index.js
  ui/app/rif/pages/rns/sell-on-mkp/index.js
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/pages/tab-definitions.js
  ui/app/rif/styleTemplate/template.css
  ui/app/root.js
  ui/app/select-app.js
Labels: enhancement, refactor, ui

#161 fix/RIFEX-297/no-undef
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/menu/index.js
  ui/app/rif/components/tokens/ChannelChiplet.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/domainsDetailPage/domainsDetailPage.js
  ui/app/rif/pages/rns/exchange/index.js
  ui/app/rif/pages/rns/register/index.js
Labels: bug, ui

#163 fix/RIFEX-299/network-after-delete
  ui/app/actions.js
Labels: bug, service layer

#162 fix/RIFEX-296/search-bar-and-resolver
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
Labels: bug, ui

#164 Fix/rifex-300/send-token-translation
  app/_locales/en/messages.json
  languages/en.json
  languages/es.json
  old-ui/app/components/pending-tx.js
  old-ui/app/components/send/send-token.js
  old-ui/app/components/token-cell.js
  old-ui/app/conf-tx.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: bug, ui

#168 RIFEX-304 Fixing domain name missing on title
  ui/app/rif/pages/rns/register/index.js
Labels: bug, ui

#167 RIFEX-305 Pre-confirmation text alignment fix
  ui/app/rif/components/modal/modal.css
Labels: bug, ui

#166 RIFEX-306 Dropdown navigation slow
  languages/en.json
  languages/es.json
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/modal-add-new-chain-address.css
Labels: bug, ui
