Repository rsksmart/rconnect, pull requests merged in 2020-06, with the labels that each got.

#27 RIFEX-85 Refactor Register Page
  ui/app/rif/actions/index.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/rns/register/index.css
  ui/app/rif/pages/rns/register/index.js
Labels: enhancement, refactor, rns, ui

#24 New Layout - UX/UI changes
  app/images/icon-back.svg
  old-ui/app/css/index.css
  ui/app/rif/components/tabs/index.css
  ui/app/rif/components/tabs/index.js
  ui/app/rif/pages/domainsPage/domain-page.css
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, rns, ui

#29 Register Page (first step) UI/UX
  ui/app/rif/pages/domainsPage/domain-page.css
  ui/app/rif/pages/rns/register/index.css
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#30 UI/UX Registration Domain Process
  old-ui/app/css/index.css
  ui/app/rif/pages/rns/register/index.css
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#28 RIFEX-86 Refactor Pay to RNS Page
  app/scripts/controllers/rif/rns/register/index.js
  old-ui/app/unlock.js
  rif/rif.config.local.js
  rif/rif.config.production.js
  rif/rif.config.staging.js
  ui/app/rif/actions/index.js
  ui/app/rif/actions/mocks.js
  ui/app/rif/components/menu/index.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/rns/pay/index.js
Labels: enhancement, refactor, rns, ui

#32 Payment Page UI/UX
  ui/app/rif/components/networks-dropdown/index.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/modal-add-new-chain-address.css
  ui/app/rif/pages/rns/pay/index.css
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#34 Adding styles to Lumino Payment option
  ui/app/rif/components/tokens-dropdown/index.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/modal-add-new-chain-address.css
  ui/app/rif/pages/rns/pay/index.js
Labels: enhancement, refactor, ui

#33 Feature/rifex 82 Generic item component in multi resolver table
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/item-with-actions/index.css
  ui/app/rif/components/item-with-actions/index.js
Labels: ui

#35 Feature/rifex 82 Subdomains List, ItemWithActions Chevron addition
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/components/subDomains.js
Labels: ui

#36 Feature/rifex 51/pay to rns domain
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/operations.js
  gulpfile.js
  ui/app/rif/actions/index.js
  ui/app/rif/actions/mocks.js
  ui/app/rif/classes/token.js
  ui/app/rif/components/index.js
  ui/app/rif/components/tokens/ChannelChiplet.js
  ui/app/rif/components/tokens/index.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/tokenDetailPage/tokenDetailPage.css
  ui/app/rif/pages/lumino/tokenDetailPage/tokenDetailPage.js
  ui/app/rif/pages/lumino/tokensPage/tokensPage.css
  ui/app/rif/pages/lumino/tokensPage/tokensPage.js
  ui/app/rif/pages/names.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/utils/channelStatus.css
  ui/app/rif/utils/parse.js
  ui/app/rif/utils/utils.js
Labels: enhancement, lumino, rns, service layer, ui

#37 UX/UI Refactor Domani Detail Page
  old-ui/app/css/index.css
  ui/app/rif/components/searchDomains.js
  ui/app/rif/components/tabs/index.css
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsPage/domain-page.css
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#40 RIFEX-77 Open channel
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/operations.js
  app/scripts/controllers/rif/lumino/signing-handler.js
  package.json
  rif.config.js
  rif/rif.config.local.js
  rif/rif.config.production.js
  rif/rif.config.staging.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/utils/validations.js
Labels: enhancement, lumino, rns, service layer, ui

#41 RIFEX-102 Close Channel
  .gitignore
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/operations.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/utils/parse.js
Labels: enhancement, rns, service layer, ui

#42 RIFEX-78 Deposit on Channel
  ui/app/rif/components/lumino/deposit-on-channel/index.js
Labels: enhancement, rns, service layer, ui

#45 UI/UX - Open channel and Deposit
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/rns/pay/index.css
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#43 RIFEX-82/Refactor-Subdomains
  app/scripts/controllers/rif/rns/resolver/index.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: refactor, ui

#31 Feature/RIFEX-84/Refactor-Domains-detail-page
  app/scripts/controllers/rif/rns/resolver/index.js
  old-ui/app/css/index.css
  package.json
  ui/app/rif/actions/index.js
  ui/app/rif/actions/mocks.js
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/customButton.js
  ui/app/rif/components/index.js
  ui/app/rif/components/item-with-actions/index.css
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/components/luminoChannels.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/components/table/genericTable.js
  ui/app/rif/components/table/index.js
  ui/app/rif/components/table/pagination.js
  ui/app/rif/components/tabs/index.css
  ui/app/rif/components/tokenNetworkChannels.js
  ui/app/rif/constants/icons.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/domainsPage/domain-page.css
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/names.js
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/styleTemplate/template.css
Labels: refactor, ui

#44 RIFEX-68 Refactor rif.config.js to be stored on nifty store instead of file
  .gitignore
  README.md
  app/scripts/controllers/rif/abstract-manager.js
  app/scripts/controllers/rif/configuration/index.js
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/lumino/explorer.js
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/operations.js
  app/scripts/controllers/rif/rns/index.js
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  gulpfile.js
  old-ui/app/components/account-dropdowns/account-dropdowns.component.js
  old-ui/app/config.js
  rif.config.js
  rif/rif.config.local.js
  rif/rif.config.production.js
  rif/rif.config.staging.js
  ui/app/rif/actions/index.js
  ui/app/rif/actions/mocks.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/configuration/index.css
  ui/app/rif/pages/configuration/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/tokensPage/tokensPage.js
  ui/app/rif/pages/names.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: enhancement, refactor, rns, service layer, ui

#46 UI/UI Refactor on domain detail and sub domains...
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/modal-add-new-chain-address.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/rns/subdomains/index.css
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#39 RIFEX-106 Lumino Networks, Network Details
  .gitignore
  README.md
  app/images/rif/chevronRight.svg
  app/images/rif/node.svg
  app/scripts/controllers/rif/abstract-manager.js
  app/scripts/controllers/rif/configuration/index.js
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/lumino/explorer.js
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/operations.js
  app/scripts/controllers/rif/rns/index.js
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  gulpfile.js
  old-ui/app/components/account-dropdowns/account-dropdowns.component.js
  old-ui/app/config.js
  rif.config.js
  rif/rif.config.local.js
  rif/rif.config.production.js
  rif/rif.config.staging.js
  ui/app/rif/actions/index.js
  ui/app/rif/actions/mocks.js
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/LuminoNetworkItem/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/components/luminoChannelItem/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/constants/index.js
  ui/app/rif/pages/configuration/index.css
  ui/app/rif/pages/configuration/index.js
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/addNewChainAddressToResolver.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewTokenNetworkAddress/modal-add-new-chain-address.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/lumino/tokensPage/tokensPage.js
  ui/app/rif/pages/names.js
  ui/app/rif/pages/rns/subdomains/index.css
  ui/app/rif/pages/rns/subdomains/index.js
  ui/app/rif/styleTemplate/template.css
  ui/app/rif/utils/parse.js
Labels: refactor, ui

#48 RIFEX-104 Fixing bugs for stores and configuration
  app/scripts/controllers/rif/abstract-manager.js
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/rns/index.js
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  app/scripts/controllers/rif/rns/transfer/index.js
Labels: bug, rns, service layer, ui

#49 RIFEX-104 Fixing Confirm Page Bugs for RSK
  app/scripts/controllers/network/enums.js
  old-ui/app/util.js
  ui/app/rif/pages/index.js
Labels: bug, rns, service layer, ui

#50 RIFEX-120/IntegrateOpenChannel
  ui/app/rif/actions/index.js
  ui/app/rif/components/commons/icons.js
  ui/app/rif/components/index.js
  ui/app/rif/components/lumino/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsPage/domainsPage.js
Labels: enhancement, refactor, ui

#52 Mocks for RIFEX-106 and table component usage
  app/scripts/controllers/rif/abstract-manager.js
  app/scripts/controllers/rif/index.js
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/rns/index.js
  app/scripts/controllers/rif/rns/register/index.js
  app/scripts/controllers/rif/rns/resolver/index.js
  app/scripts/controllers/rif/rns/rns-delegate.js
  app/scripts/controllers/rif/rns/rnsjs-delegate.js
  app/scripts/controllers/rif/rns/transfer/index.js
  ui/app/rif/actions/index.js
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
Labels: refactor, ui

#53 Feature/rifex 122/refactor modals
  ui/app/rif/actions/index.js
  ui/app/rif/components/modal/modal.css
  ui/app/rif/components/tabs/index.css
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActiveConfig/index.css
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#55 Fix PR Comments on RIFEX-106
  ui/app/rif/actions/index.js
  ui/app/rif/pages/lumino/index.js
Labels: enhancement, ui

#47 Feature/rifex 106/lumino networks channels
  app/images/rif/channels-circle.svg
  app/images/rif/channels.svg
  app/images/rif/chevronRight.svg
  app/images/rif/node.svg
  ui/app/rif/actions/index.js
  ui/app/rif/components/LuminoNetworkItem/index.js
  ui/app/rif/components/domain-header/index.js
  ui/app/rif/components/luminoChannelItem/index.js
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/index.css
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/names.js
  ui/app/rif/styleTemplate/template.css
  ui/app/rif/utils/parse.js
Labels: enhancement, refactor, ui

#54 Feature/rifex 80 Generic Search Bar and usages
  ui/app/rif/components/LuminoNetworkItem/index.js
  ui/app/rif/components/genericSearch/index.js
  ui/app/rif/components/index.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/components/searchLuminoNetworks/index.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/index.css
  ui/app/rif/pages/lumino/index.css
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/tab-definitions.js
Labels: enhancement, ui

#58 RIFEX-116/Adding-Row-Update-Pagination
  ui/app/rif/components/table/pagination.js
Labels: bug

#57 RIFEX-119/Bug-Deleting-Unique-Row
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/subDomains.js
Labels: bug, ui

#56 RIFEX-121 Reinitialize LC SDK
  app/scripts/controllers/rif/lumino/index.js
Labels: enhancement, refactor

#59 Fix RIFEX-127 unique storage keys
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/storage.js
Labels: bug

#60 RIFEX-113/Add-lumino icon
  app/scripts/controllers/rif/lumino/explorer.js
  app/scripts/controllers/rif/lumino/index.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/commons/icons.js
  ui/app/rif/components/domain-header/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
Labels: enhancement, ui

#61 RIFEX-128 Fix search bar prop
  ui/app/rif/components/searchDomains.js
Labels: bug

#51 RIFEX-54/Lumino-Channels-Detail
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/components/lumino/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/components/tabs/index.css
  ui/app/rif/components/tabs/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/index.css
  ui/app/rif/pages/lumino/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/names.js
  ui/app/rif/pages/rns/lumino-channels/index.css
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/pages/rns/subdomains/index.css
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#62 RIFEX-129/Fix-Array-Comparission
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/utils/utils.js
Labels: bug

#63 RIFEX-130/Bug-Fix-Subdomain-details
  ui/app/rif/pages/rns/subdomains/index.js
Labels: bug

#65 RIFEX-135 Apply css classes for Select
  ui/app/rif/components/lumino/open-channel/index.css
  ui/app/rif/components/lumino/open-channel/index.js
Labels: ui

#64 RIFEX-133/OpenChannel-Update-Table
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: bug

#67 RIFEX-137 Deposit failing when we open channel
  ui/app/rif/components/lumino/open-channel/index.js
Labels: bug, ui

#66 RIFEX-136/Callback-CloseChannel
  app/scripts/controllers/rif/lumino/operations.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: bug

#68 Bug/rifex 132/fixing back
  ui/app/rif/actions/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/rns/register/index.js
Labels: bug, rns, ui

#69 RIFEX-131/Fixes-For-Demo
  app/scripts/controllers/rif/lumino/operations.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.css
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/pages/rns/subdomains/index.js
Labels: bug

#74 RIFEX-153 Validate deposit amount
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/utils/validations.js
Labels: bug, ui

#70 RIFEX-150 Changing change label to save
  ui/app/rif/actions/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/addNewSubdomain/index.js
Labels: bug, ui

#76 RIFEX-158 Show Off chain balance
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
Labels: bug, ui

#72 RIFEX-146 Proper subdomain names order
  ui/app/rif/pages/rns/subdomains/index.js
Labels: ui

#73 RIFEX-145 Ellipsis on long subdomain names
  ui/app/rif/components/domain-header/index.js
  ui/app/rif/pages/domainsDetailPage/domain-detail-page.css
Labels: ui

#75 RIFEX-151 Search without enter in some inputs
  ui/app/rif/components/genericSearch/index.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/utils/utils.js
Labels: enhancement

#71 Only show titles when explicitly requested RIFEX-143
  ui/app/rif/actions/index.js
  ui/app/rif/components/luminoNetworkChannels.js
  ui/app/rif/components/searchDomains.js
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
  ui/app/rif/pages/domainsPage/domainsPage.js
  ui/app/rif/pages/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/register/index.js
  ui/app/rif/pages/tab-definitions.js
Labels: bug, ui

#77 RIFEX-154 Refresh network data in all cases
  ui/app/rif/actions/index.js
Labels: bug

#80 RIFEX-139, UI Refactor on Config Page
  ui/app/rif/pages/configuration/index.css
  ui/app/rif/pages/configuration/index.js
  ui/app/rif/pages/index.js
  ui/app/rif/styleTemplate/template.css
Labels: enhancement, refactor, ui

#78 RIFEX-134/Generic-table-Not-Staying
  ui/app/rif/components/table/genericTable.js
  ui/app/rif/components/table/pagination.js
Labels: bug

#79 RIFEX-163/Subdomains-Table-Not-Refreshing
  ui/app/rif/components/subDomains.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
Labels: bug

#81 RIFEX-160 Loader spinner on operations
  app/scripts/controllers/rif/lumino/index.js
  app/scripts/controllers/rif/lumino/storage.js
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/common-style-pages.css
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
  ui/app/rif/pages/rns/pay/index.js
  ui/app/rif/utils/components.js
Labels: enhancement, rns, service layer, ui

#82 RIFEX-161 Fixing default callbacks for lumino
  app/scripts/controllers/rif/constants/lumino.js
  app/scripts/controllers/rif/index.js
  old-ui/app/app.js
  old-ui/app/unlock.js
  ui/app/reducers/app.js
  ui/app/rif/actions/index.js
  ui/app/rif/reducers/index.js
Labels: bug, service layer, ui

#85 RIFEX-149/Set-Address-Change-Input
  ui/app/rif/components/InputWithSubmit/index.js
  ui/app/rif/components/chainAddresses.js
Labels: enhancement, ui

#84 RIFEX-157/Change-Label-Close
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: enhancement, ui

#86 RIFEX-155 Deposit real time update
  app/scripts/controllers/rif/lumino/callbacks.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/lumino/close-channel/index.js
  ui/app/rif/components/lumino/deposit-on-channel/index.js
  ui/app/rif/components/lumino/open-channel/index.js
  ui/app/rif/pages/lumino/luminoNetworkDetails/index.js
  ui/app/rif/pages/rns/lumino-channels/index.js
Labels: bug, refactor, rns, service layer, ui

#83 RIFEX-141/Order-Chainaddresses
  ui/app/rif/components/chainAddresses.js
Labels: enhancement, ui

#87 RIFEX-142/Not-showing-actions-when-deleting
  app/scripts/controllers/rif/rns/classes/chainAddress.js
  app/scripts/controllers/rif/rns/resolver/index.js
  ui/app/rif/actions/index.js
  ui/app/rif/components/chainAddresses.js
  ui/app/rif/components/item-with-actions/index.js
  ui/app/rif/pages/domainsDetailPage/domainDetailActive/domainDetailActive.js
Labels: enhancement, ui
